스칼라(0D텐서)

In [1]:
import numpy as np

In [2]:
x = np.array(12)

In [3]:
x

array(12)

In [4]:
x.ndim

0

벡터(1D텐서)


In [6]:
x = np.array([12, 3, 6, 14, 7])

1

In [7]:
x

array([12,  3,  6, 14,  7])

In [8]:
x.ndim

1

행렬(2D텐서)


In [9]:
x = np.array([[5, 78, 2, 34, 0],
              [6, 79, 3, 35, 1],
              [7, 80, 4, 36,2]])

In [10]:
x

array([[ 5, 78,  2, 34,  0],
       [ 6, 79,  3, 35,  1],
       [ 7, 80,  4, 36,  2]])

In [11]:
x.ndim

2

3D 텐와 고차원 텐서


In [16]:
x = np.array([
              [[5, 78, 3, 34, 0],
               [6, 79, 3, 36,1],
                [7, 80, 4, 36, 2]],
              
               [[5, 78, 2, 34, 0],
                [6, 79, 3, 35, 1],
                [7, 80, 4, 34, 2]],
              
               [[5, 78, 2, 34, 0],
                [6, 79, 3, 35, 1],
                [7, 80, 4, 36, 7]]
               ])

In [17]:
x

array([[[ 5, 78,  3, 34,  0],
        [ 6, 79,  3, 36,  1],
        [ 7, 80,  4, 36,  2]],

       [[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 34,  2]],

       [[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  7]]])

In [18]:
x.ndim

3