<a href="https://colab.research.google.com/github/mkbahk/DeepLearningwithKeras/blob/master/2_3_%EC%8B%A0%EA%B2%BD%EB%A7%9D%EC%9D%98_%ED%86%B1%EB%8B%88%EB%B0%94%ED%80%B4_%ED%85%90%EC%84%9C_%EC%97%B0%EC%82%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
def naive_relu(x):
  assert len(x.shape) == 2 #x는 2D 넘파이 배열입니다.

  x = x.copy() #입력 텐서 자체를 바꾸지 않도록 복사합니다.

  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i, j] = max(x[i, j], 0)
  return x
#end of def

def naive_add(x, y):
  assert len(x.shape) == 2 # x와 y는 넘파이 배열입니다.
  assert len(y.shape) == 2
  assert x.shape == y.shape

  x = x.copy() #입력텐서 자체를 바꾸지 않습니다.

  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i, j] += y[i, j]
  return x
#end of def

def naive_add_matrix_and_vector(x, y):
  assert len(x.shape) == 2 # x는 2D 넘파이 배열입니다.
  assert len(y.shape) == 1 # y는 넘파이 1D벡터입니다.
  assert x.shape[1] == y.shape[0]

  x = x.copy() #입력 텐서 자체를 바꾸지 않토록 복사합니ㅏㄷ.

  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i, j] += y[j]
  return x
#end of def


In [10]:
import numpy as np

In [11]:
x = np.array([[5, 78, 2, 34, 0],
             [6, 79, 3, 35, 1],
             [7, 80, 4, 36, 2]])
print(naive_relu(x))

[[ 5 78  2 34  0]
 [ 6 79  3 35  1]
 [ 7 80  4 36  2]]


In [21]:
y = np.array([[5, 78, 2, 34, -1],
             [6, 79, 3, 35, -1],
             [7, 80, 4, 36, 2]])
print(naive_add(x, y))

[[ 10 156   4  68  -1]
 [ 12 158   6  70   0]
 [ 14 160   8  72   4]]


In [22]:
z = x + y
print(z)

[[ 10 156   4  68  -1]
 [ 12 158   6  70   0]
 [ 14 160   8  72   4]]


In [23]:
z = np.maximum(z, 0.) # 원소별 렐루 함수
print(z)

[[ 10. 156.   4.  68.   0.]
 [ 12. 158.   6.  70.   0.]
 [ 14. 160.   8.  72.   4.]]


In [28]:
x = np.random.random((64, 3, 32, 10)) # x는 (64, 3, 32, 10) 크기의 랜덤 텐서입니다.
y = np.random.random((32, 10)) # Y는 (32, 10) 크기의 램덤 텐서입니다.

z = np.maximum(x, y)
print(z)

[[[[0.43206529 0.62564795 0.92005632 ... 0.2186561  0.48628991
    0.6980358 ]
   [0.60968498 0.68157364 0.96750966 ... 0.49392467 0.82542238
    0.45490522]
   [0.68228497 0.39551803 0.3752676  ... 0.52156929 0.90935473
    0.98254236]
   ...
   [0.5335588  0.5947805  0.75564978 ... 0.62759721 0.78695602
    0.81235554]
   [0.7154964  0.65098654 0.71045368 ... 0.67084549 0.77689761
    0.5645491 ]
   [0.5248283  0.51456512 0.93879914 ... 0.86176692 0.19913357
    0.53833942]]

  [[0.80723889 0.75729262 0.33803982 ... 0.20148934 0.50384209
    0.88755318]
   [0.75803482 0.96935576 0.96750966 ... 0.84808016 0.82542238
    0.47951794]
   [0.38002228 0.10746382 0.19405858 ... 0.52156929 0.78757146
    0.98254236]
   ...
   [0.5335588  0.89074772 0.42866264 ... 0.62759721 0.78146509
    0.59307765]
   [0.56257784 0.70754411 0.58858392 ... 0.91054265 0.77689761
    0.96163788]
   [0.89928748 0.64805064 0.93879914 ... 0.9876653  0.19913357
    0.62671528]]

  [[0.43206529 0.58115901 0.213656

In [33]:
x = np.random.random((64, 3, 50)) # x는 (64, 3, 32, 10) 크기의 랜덤 텐서입니다.
y = np.random.random((32, 10, 50, 80)) # Y는 (32, 10) 크기의 램덤 텐서입니다.

z = np.dot(x, y)
print(z)

[[[[[15.44018427 12.63339621 13.81896381 ... 12.98473868 12.61108265
     14.73102575]
    [16.71681301 12.97423512 15.72185142 ... 14.61100506 11.54156958
     14.19249378]
    [15.77857814 12.16088384 14.23590467 ... 12.51808298 14.02886841
     12.18901656]
    ...
    [14.24747478 13.72534884 14.7872832  ... 13.41312837 12.6862175
     11.77492964]
    [13.71441379 13.62293755 13.94899628 ... 13.92467892 15.78968623
     11.09098618]
    [14.43405042 13.28206066 15.17318938 ... 13.30173494 12.7784582
     13.46798417]]

   [[15.05551745 14.71058564 14.48773845 ... 11.66282602 11.4678383
     15.00946907]
    [12.95137236 13.25583209 13.56393338 ... 16.19575263 15.53904101
     15.45292859]
    [12.14666163 15.12990287 14.72024373 ... 13.57733477 14.56751638
     14.12473731]
    ...
    [13.62384989 11.58756842 14.71041312 ... 14.33998104 14.51681207
     15.0744519 ]
    [13.28393758 13.58380139 13.00845687 ... 13.61916217 12.85254201
     12.44187815]
    [11.8040802  13.02575703