Module Import

In [24]:
from tensorflow import keras

Load MNIST DataSet


In [25]:
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

In [26]:
for i in range(5):
  print(y_train[i])

5
0
4
1
9


one-hot enconding 수행
5 --> 0 0 0 0 0 1 0 0 0 0
1 --> 0 1 0 0 0 0 0 0 0 0


In [27]:
y_train = keras.utils.to_categorical(y=y_train, num_classes = 10)
y_test = keras.utils.to_categorical(y=y_test, num_classes=10)

for i in range(5):
  print(y_train[i])

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


Reshaping DataSet


In [28]:
x_train = x_train.reshape(60000, 28*28)
x_test = x_test.reshape(10000, 28*28)
print(y_train.shape, y_test.shape)
print(x_train.shape, x_test.shape)

(60000, 10) (10000, 10)
(60000, 784) (10000, 784)


모델 생성


In [29]:
model = keras.Sequential()
model.add(keras.layers.Dense(32, activation="sigmoid", input_shape=(28*28,)))
model.add(keras.layers.Dense(32, activation="sigmoid"))
model.add(keras.layers.Dense(10, activation="sigmoid"))

모델컴파일

In [30]:
model.compile(optimizer=keras.optimizers.SGD(learning_rate=0.1), loss="categorical_crossentropy", metrics=['accuracy'])
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 32)                25120     
_________________________________________________________________
dense_7 (Dense)              (None, 32)                1056      
_________________________________________________________________
dense_8 (Dense)              (None, 10)                330       
Total params: 26,506
Trainable params: 26,506
Non-trainable params: 0
_________________________________________________________________


모델훈련


In [31]:
from keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(patience=15, mode='auto', monitor='val_accuracy')

model.fit(x=x_train, y=y_train, batch_size=128, epochs=100, validation_data=(x_test, y_test), callbacks=[early_stopping])

Epoch 1/100
469/469 [==============================] - 1s 2ms/step - loss: 1.7269 - accuracy: 0.6176 - val_loss: 1.0420 - val_accuracy: 0.8084
Epoch 2/100
469/469 [==============================] - 1s 2ms/step - loss: 0.8235 - accuracy: 0.8161 - val_loss: 0.6118 - val_accuracy: 0.8611
Epoch 3/100
469/469 [==============================] - 1s 2ms/step - loss: 0.6052 - accuracy: 0.8440 - val_loss: 0.5264 - val_accuracy: 0.8671
Epoch 4/100
469/469 [==============================] - 1s 2ms/step - loss: 0.5573 - accuracy: 0.8459 - val_loss: 0.4921 - val_accuracy: 0.8635
Epoch 5/100
469/469 [==============================] - 1s 2ms/step - loss: 0.5388 - accuracy: 0.8459 - val_loss: 0.5042 - val_accuracy: 0.8600
Epoch 6/100
469/469 [==============================] - 1s 2ms/step - loss: 0.5067 - accuracy: 0.8533 - val_loss: 0.4990 - val_accuracy: 0.8528
Epoch 7/100
469/469 [==============================] - 1s 2ms/step - loss: 0.5015 - accuracy: 0.8530 - val_loss: 0.5077 - val_accuracy: 0.8531

모델 평가


In [32]:
model.evaluate(x_test, y_test )

313/313 [==============================] - 0s 948us/step - loss: 0.2883 - accuracy: 0.9124


[0.28829649090766907, 0.9124000072479248]