In [37]:
import numpy as np
import pandas as pd
import matplotlib as mp
import tensorflow as tf

In [38]:
print("numpy version ", np.__version__)
print("pandas version ", pd.__version__)
print("matplotlib version ", mp.__version__)
print("tensorflow version ", tf.__version__)

numpy version  1.18.5
pandas version  1.1.4
matplotlib version  3.2.2
tensorflow version  2.3.0


In [39]:
import numpy
A = numpy.array([1, 2])
print("A ==", A, ", type ==", type(A))

A == [1 2] , type == <class 'numpy.ndarray'>


In [40]:
import numpy as np
A = np.array([1, 2])
print("A ==", A, ", type ==", type(A))

A == [1 2] , type == <class 'numpy.ndarray'>


In [41]:
from numpy import exp
A  = exp(1)
print("A ==", A, ", type ==", type(A))

A == 2.718281828459045 , type == <class 'numpy.float64'>


In [42]:
from numpy import *
A = exp(1) + log(1.7) + sqrt(2)
print("A ==", A, ", type ==", type(A))

A == 4.663123641894311 , type == <class 'numpy.float64'>


numpy 연산들

vector /matrix 생성

행렬곱(dot product)

broadcast

index / slice /iterator

concatenate

useful function(loadtxt(), rand(), argmax())

In [43]:
import numpy as np
A = [[1, 0], [0, 1]]
B = [[1, 1], [1, 1]]
print(A + B)

[[1, 0], [0, 1], [1, 1], [1, 1]]


In [44]:
A = np.array([[1, 0], [0, 1]])
B = np.array([[1, 1], [1, 1]])
print(A + B)

[[2 1]
 [1 2]]


In [45]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# vector A, B 값 출력
print("A ==", A, "\n", "B ==", B)

# vector A, B 형상 출력 => shape
print("A.shape ==", A.shape, ", B.shape ==", B.shape)

# vector A, B 차원 출력 => ndim
print("A.ndim ==", A.ndim, ", B.ndim ==", B.ndim)


A == [1 2 3] 
 B == [4 5 6]
A.shape == (3,) , B.shape == (3,)
A.ndim == 1 , B.ndim == 1


In [46]:
# vector 산술연산

print("A + B ==", A + B)
print("A - B ==", A - B)
print("A * B ==", A * B)
print("A / B ==", A / B)

A + B == [5 7 9]
A - B == [-3 -3 -3]
A * B == [ 4 10 18]
A / B == [0.25 0.4  0.5 ]


In [47]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[-1, -2, -3], [-4, -5, -6]])

# vector A, B 값 출력
print("A ==", A, "\n", "B ==", B)

# vector A, B 형상 출력 => shape
print("A.shape ==", A.shape, ", B.shape ==", B.shape)

# vector A, B 차원 출력 => ndim
print("A.ndim ==", A.ndim, ", B.ndim ==", B.ndim)

A == [[1 2 3]
 [4 5 6]] 
 B == [[-1 -2 -3]
 [-4 -5 -6]]
A.shape == (2, 3) , B.shape == (2, 3)
A.ndim == 2 , B.ndim == 2


In [48]:
# matrix 산술연산

print("A + B ==", A + B)
print("A - B ==", A - B)
print("A * B ==", A * B)
print("A / B ==", A / B)

A + B == [[0 0 0]
 [0 0 0]]
A - B == [[ 2  4  6]
 [ 8 10 12]]
A * B == [[ -1  -4  -9]
 [-16 -25 -36]]
A / B == [[-1. -1. -1.]
 [-1. -1. -1.]]


In [50]:
# 형변환
C = np.array([1, 2, 3])

# vector C형상 출력 => shape
print("C.shape ==", C.shape, "벡터")
print(C)

# vector를 (1, 3) 행렬로 형 변환
C = C.reshape(1, 3)
print("C.shape ==", C.shape, "행력")
print(C)

C.shape == (3,) 벡터
[1 2 3]
C.shape == (1, 3) 행력
[[1 2 3]]
