In [1]:
import numpy as np

In [7]:
A = np.array([[10, 20, 30], [40, 50, 60]])
print(A.shape)
print(A)

(2, 3)
[[10 20 30]
 [40 50 60]]


In [8]:
row_add = np.array([70, 80, 90]).reshape(1, 3)
print(row_add.shape)
print(row_add)

(1, 3)
[[70 80 90]]


In [9]:
column_add = np.array([1000, 2000]).reshape(2, 1)
print(column_add.shape)
print(column_add)

(2, 1)
[[1000]
 [2000]]


In [6]:
B = np.concatenate((A, row_add), axis=0)
print(B)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [10]:
C = np.concatenate((A, column_add), axis=1)
print(C)

[[  10   20   30 1000]
 [  40   50   60 2000]]
