<a href="https://colab.research.google.com/github/mkbahk/DeepLearningwithKeras/blob/master/eMNIST_CPU_Sample.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Module Import

In [ ]:
from tensorflow import keras

Load MNIST DataSet


In [ ]:
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [ ]:
for i in range(5):
  print(y_train[i])

5
0
4
1
9


one-hot enconding 수행
5 --> 0 0 0 0 0 1 0 0 0 0
1 --> 0 1 0 0 0 0 0 0 0 0


In [ ]:
y_train = keras.utils.to_categorical(y=y_train, num_classes = 10)
y_test = keras.utils.to_categorical(y=y_test, num_classes=10)

for i in range(5):
  print(y_train[i])

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


Reshaping DataSet


In [ ]:
x_train = x_train.reshape(60000, 28*28)
x_test = x_test.reshape(10000, 28*28)
print(y_train.shape, y_test.shape)
print(x_train.shape, x_test.shape)

(60000, 10) (10000, 10)
(60000, 784) (10000, 784)


모델 생성


In [ ]:
model = keras.Sequential()
model.add(keras.layers.Dense(32, activation="sigmoid", input_shape=(28*28,)))
model.add(keras.layers.Dense(32, activation="sigmoid"))
model.add(keras.layers.Dense(10, activation="sigmoid"))

모델컴파일

In [ ]:
model.compile(optimizer=keras.optimizers.SGD(learning_rate=0.1), loss="categorical_crossentropy", metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 32)                25120     
_________________________________________________________________
dense_1 (Dense)              (None, 32)                1056      
_________________________________________________________________
dense_2 (Dense)              (None, 10)                330       
Total params: 26,506
Trainable params: 26,506
Non-trainable params: 0
_________________________________________________________________


모델훈련


In [ ]:
model.fit(x=x_train, y=y_train, batch_size=128, epochs=100, validation_data=(x_test, y_test))

Epoch 1/100
469/469 [==============================] - 1s 3ms/step - loss: 1.6855 - accuracy: 0.6381 - val_loss: 1.0478 - val_accuracy: 0.7899
Epoch 2/100
469/469 [==============================] - 1s 3ms/step - loss: 0.8013 - accuracy: 0.8192 - val_loss: 0.6450 - val_accuracy: 0.8394
Epoch 3/100
469/469 [==============================] - 1s 3ms/step - loss: 0.6288 - accuracy: 0.8358 - val_loss: 0.5481 - val_accuracy: 0.8611
Epoch 4/100
469/469 [==============================] - 1s 3ms/step - loss: 0.5744 - accuracy: 0.8395 - val_loss: 0.5500 - val_accuracy: 0.8510
Epoch 5/100
469/469 [==============================] - 1s 3ms/step - loss: 0.5497 - accuracy: 0.8423 - val_loss: 0.5295 - val_accuracy: 0.8509
Epoch 6/100
469/469 [==============================] - 1s 3ms/step - loss: 0.5312 - accuracy: 0.8448 - val_loss: 0.5019 - val_accuracy: 0.8423
Epoch 7/100
469/469 [==============================] - 1s 3ms/step - loss: 0.5011 - accuracy: 0.8503 - val_loss: 0.4847 - val_accuracy: 0.8561

모델 평가


In [ ]:
model.evaluate(x_test, y_test )

313/313 [==============================] - 0s 979us/step - loss: 0.2494 - accuracy: 0.9225


[0.24936574697494507, 0.9225000143051147]