<a href="https://colab.research.google.com/github/mkbahk/DeepLearningwithKeras/blob/master/%EB%A8%B8%EC%89%B0%EB%9F%AC%EB%8B%9D%EA%B0%95%EC%A2%8C_numpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
a = np.array([[1, 2, 3], [4, 5,6]])  # 2x3 행렬
b = np.array([[-1, -2], [-3, -4], [-5, -6]])   #3x2행렬

# (2x3) dot product (3x2) == (2x2) 행렬

In [4]:
c = np.dot(a, b)

# matrix a, b 형상 출력 => shape
print("a.shape ==", a.shape, ", b.shape ==", b.shape)
print("c.shape ==", c.shape)
print(c)

a.shape == (2, 3) , b.shape == (3, 2)
c.shape == (2, 2)
[[-22 -28]
 [-49 -64]]


numpy broadcast:

행력의 사칙연산은 기본적으로 두 개의 행렬 크기가 같은 경우에만 수행할 수 있으나, numpy에서는 크기가 다른 두 행력간에도 사칙연산(+, -, *, /)을 할 수 있도록 하는데 이것은 브로드케스트(broadcast)라 한다.

In [6]:
a = [[1, 2], [3,4]]
b = 5

print(a + b)

TypeError: ignored

In [11]:
a = [[1, 2], [3,4]]
b = [5]

print(a + b)

[[1, 2], [3, 4], 5]


In [10]:
a = [[1, 2], [3,4]]
b = [5]

print(a - b)

TypeError: ignored

In [12]:
a = [[1, 2], [3,4]]
b = [5]

print(a * b)

TypeError: ignored

In [13]:
a = [[1, 2], [3,4]]
b = [5]

print(a / b)

TypeError: ignored

In [5]:
a =  np.array([[1, 2], [3, 4]])
b = 5

print(a + b)

[[6 7]
 [8 9]]


In [14]:
a =  np.array([[1, 2], [3, 4]])
b = 5

print(a * b)

[[ 5 10]
 [15 20]]


In [15]:
a =  np.array([[1, 2], [3, 4]])
b = 5

print(a - b)

[[-4 -3]
 [-2 -1]]


In [16]:
a =  np.array([[1, 2], [3, 4]])
b = 5

print(a / b)

[[0.2 0.4]
 [0.6 0.8]]


전치행렬(transpose)

In [17]:
A = np.array([ [1,2], [3, 4], [5, 6]])

B = A.T #A의 전치행력, 2x3 행렬,  .T 연산자

print("A.shape ==", A.shape, ", B.shape ==", B.shape)
print(A)
print(B)

A.shape == (3, 2) , B.shape == (2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [19]:
# Vector 전치행렬

C = np.array([1, 2, 3, 4, 5]) # vector임, matrix 아님
D = C.T   #C는 벡터이므로 transpose 않됨

E = C.reshape(1, 5) # 1x5 matrix
F = E.T

print("C.shape ==", C.shape, ", D.shape ==", D.shape)
print("E.shape ==", E.shape, ", F.shape ==", F.shape)
print(F)

C.shape == (5,) , D.shape == (5,)
E.shape == (1, 5) , F.shape == (5, 1)
[[1]
 [2]
 [3]
 [4]
 [5]]


numpy 행렬 indexing / slicing

In [25]:
A = np.array([10, 20, 30, 40, 50, 60]).reshape(3,2)
print("A.shape ==", A.shape)
print(A)

print("A[0, 0] ==", A[0, 0], ", A[0][0] ==", A[0][0])
print("A[2, 1] ==", A[2, 1], ", A[2][1] ==", A[1][1])

#왜 값이 틀릴까요?
print("A[0:-1, 1:2] ==", A[0:-1,  1:2])
print("A[0:-1][1:2] ==", A[0:-1][1:2])

print("A[:, 0] == ", A[:, 0])
print("A[:, :] == ", A[:, :])

A.shape == (3, 2)
[[10 20]
 [30 40]
 [50 60]]
A[0, 0] == 10 , A[0][0] == 10
A[2, 1] == 60 , A[2][1] == 40
A[0:-1, 1:2] == [[20]
 [40]]
A[0:-1][1:2] == [[30 40]]
A[:, 0] ==  [10 30 50]
A[:, :] ==  [[10 20]
 [30 40]
 [50 60]]


numpy 행렬 iterator

In [27]:
A =  np.array([[10,20,30,40], [50, 60, 70, 80]])

print(A, "\n")
print("A.shape ==", A.shape, "\n")

#행렬 A의 itrator 생성

it = np.nditer(A, flags=['multi_index'], op_flags=['readwrite'])

while not it.finished:
  idx = it.multi_index
  print("Current Value => ", A[idx])
  it.iternext()
# end of while


[[10 20 30 40]
 [50 60 70 80]] 

A.shape == (2, 4) 

Current Value =>  10
Current Value =>  20
Current Value =>  30
Current Value =>  40
Current Value =>  50
Current Value =>  60
Current Value =>  70
Current Value =>  80
